const PathConstants = {
    HOME: "/",
    SHOPPAGE: "/shop-page",
    OURTEAMPAGE: "our-team-page",
    OURIMPACTPAGE: "our-impact-page",
    GIFTCARDPAGE: "gift-card-page",
    FAQPAGE: "faq-page",
    JOURNALPAGE: "/journal-page",
    CONTACTSPAGE: "contacts-page",
    COMINGSOONPAGE: "coming-soon-page",
    SHIRTCARDPAGE: "shirt-card-page",
    T_SHIRTCARDPAGE: "t-shirt-card-page",
    BOTTOMCARDPAGE: "bottom-card-page",
    ROOMPERCARDPAGE: "roomper-card-page",
    HATCARDPAGE: "hat-card-page",
    ARTICLE01PAGE: "/article01-page",
    ARTICLE02PAGE: "/article02-page",
    ARTICLE03PAGE: "/article03-page",
    ARTICLE04PAGE: "/article04-page",
    ARTICLE05PAGE: "/article05-page",
    ARTICLE06PAGE: "/article06-page",
}
export default PathConstants;