export const allCategories = [{
    id: "shi01",
    cardLink: "/shirt-card-page",
    imgSrc: "/recommendations-image01.jpg",
    imgAlt: "Children's long sleeve shirt",
    caption: "Birch Shirt in Sand",
    stars: "/five-star-rating.png",
    reviews: "2 reviews",
    price: "45.00 USD",
    cotton: "",
    linen: "linen",
}, {
    id: "shi02",
    cardLink: "/shirt-card-page",
    imgSrc: "/recommendations-image15.jpg",
    imgAlt: "Children's shirt with hood",
    caption: "Shirt With Hood",
    stars: "/five-star-rating.png",
    reviews: "4 reviews",
    price: "66.00 USD",
    cotton: "cotton",
    linen: "",
}, {
    id: "shi03",
    cardLink: "/shirt-card-page",
    imgSrc: "/recommendations-image14.jpg",
    imgAlt: "Children's long sleeve shirt",
    caption: "Shirt With Checks",
    stars: "/five-star-rating.png",
    reviews: "5 reviews",
    price: "51.00 USD",
    cotton: "cotton",
    linen: "",
}, {
    id: "t_sh01",
    cardLink: "/t-shirt-card-page",
    imgSrc: "/recommendations-image02.jpg",
    imgAlt: "Child T-shirt",
    caption: "Oak Tee",
    stars: "/five-star-rating.png",
    reviews: "3 reviews",
    price: "34.00 USD",
    cotton: "cotton",
    linen: "",
}, {
    id: "t_sh02",
    cardLink: "/t-shirt-card-page",
    imgSrc: "/recommendations-image05.jpg",
    imgAlt: "Child T-shirt",
    caption: "Willow Tee",
    stars: "/five-star-rating.png",
    reviews: "1 reviews",
    price: "34.00 USD",
    cotton: "cotton",
    linen: "",
}, {
    id: "t_sh03",
    cardLink: "/t-shirt-card-page",
    imgSrc: "/recommendations-image07.jpg",
    imgAlt: "Child T-shirt",
    caption: "Oak Henley Tee",
    stars: "/five-star-rating.png",
    reviews: "2 reviews",
    price: "34.00 USD",
    cotton: "cotton",
    linen: "",
}, {
    id: "bot01",
    cardLink: "/bottom-card-page",
    imgSrc: "/recommendations-image04.jpg",
    imgAlt: "Children's trousers with pockets",
    caption: "Oak Pant in Tassel",
    stars: "/five-star-rating.png",
    reviews: "5 reviews",
    price: "52.00 USD",
    cotton: "cotton",
    linen: "",
}, {
    id: "bot02",
    cardLink: "/bottom-card-page",
    imgSrc: "/recommendations-image08.jpg",
    imgAlt: "Children's trousers with pockets",
    caption: "Gingko Pant in Ripe Olive",
    stars: "/five-star-rating.png",
    reviews: "5 reviews",
    price: "42.00 USD",
    cotton: "",
    linen: "linen",
}, {
    id: "bot03",
    cardLink: "/bottom-card-page",
    imgSrc: "/recommendations-image10.jpg",
    imgAlt: "Children's shorts with drawstring",
    caption: "Oak Short in Naval",
    stars: "/five-star-rating.png",
    reviews: "2 reviews",
    price: "45.00 USD",
    cotton: "",
    linen: "linen",
}, {
    id: "roo01",
    cardLink: "/roomper-card-page",
    imgSrc: "/recommendations-image03.jpg",
    imgAlt: "Rompers",
    caption: "Birch Romper in Sleepy Blue",
    stars: "/five-star-rating.png",
    reviews: "1 reviews",
    price: "62.00 USD",
    cotton: "",
    linen: "linen",
}, {
    id: "roo02",
    cardLink: "/roomper-card-page",
    imgSrc: "/recommendations-image06.jpg",
    imgAlt: "Children's shirt with short sleeves",
    caption: "Maple Romper in Canyon Clay",
    stars: "/five-star-rating.png",
    reviews: "3 reviews",
    price: "70.00 USD",
    cotton: "",
    linen: "linen",
}, {
    id: "roo03",
    cardLink: "/roomper-card-page",
    imgSrc: "/recommendations-image09.jpg",
    imgAlt: "Children's overalls with straps",
    caption: "Ginkgo Romper in Tassel",
    stars: "/five-star-rating.png",
    reviews: "2 reviews",
    price: "62.00 USD",
    cotton: "",
    linen: "linen",
}, {
    id: "hat01",
    cardLink: "/hat-card-page",
    imgSrc: "/recommendations-image11.jpg",
    imgAlt: "Children's straw hat",
    caption: "Natural Straw Hat",
    stars: "/five-star-rating.png",
    reviews: "4 reviews",
    price: "22.00 USD",
    cotton: "",
    linen: "",
}, {
    id: "hat02",
    cardLink: "/hat-card-page",
    imgSrc: "/recommendations-image12.jpg",
    imgAlt: "Children's denim bucket hat",
    caption: "Hat In Blue Denim",
    stars: "/five-star-rating.png",
    reviews: "3 reviews",
    price: "29.00 USD",
    cotton: "cotton",
    linen: "",
}, {
    id: "hat03",
    cardLink: "/hat-card-page",
    imgSrc: "/recommendations-image13.jpg",
    imgAlt: "Children's round hat",
    caption: "Round Beige Hat",
    stars: "/five-star-rating.png",
    reviews: "5 reviews",
    price: "26.00 USD",
    cotton: "cotton",
    linen: "",
}]