export const latestArticles = [{
    id: "latArt01",
    imageSrc: "/latest-article01-image.jpeg",
    imageAlt: "Girl in a shelf of dandelions",
    linkTitle: "/article05-page",
    date: "02.06.2023",
    title: "The Ultimate Guide to Building a Capsule Wardrobe for Your Kids",
    text: "As parents, we all know the struggle of getting our kids dressed every day...",
    readLink: "/article05-page",
    linkText: "Read more",
    readLinkSrc: "/svg/shop-gallery-link-arrow.svg",
}, {
    id: "latArt02",
    imageSrc: "/latest-article02-image.jpeg",
    imageAlt: "Basket with laundry",
    linkTitle: "/article06-page",
    date: "02.06.2023",
    title: "Laundry Hacks for Eco-Conscious Parents: How to Extend the Life of Your...",
    text: "Constantly replacing clothes isn't just tough on our wallets – it's also tough...",
    readLink: "/article06-page",
    linkText: "Read more",
    readLinkSrc: "/svg/shop-gallery-link-arrow.svg",
}, {
    id: "latArt03",
    imageSrc: "/latest-article03-image.jpeg",
    imageAlt: "Two girls hugging",
    linkTitle: "/coming-soon-page",
    date: "02.06.2023",
    title: "Breaking Down Gender Stereotypes: Why Gender-Neutral Clothing is...",
    text: "As parents, we all want our kiddos to feel comfortable and confident...",
    readLink: "/coming-soon-page",
    linkText: "Read more",
    readLinkSrc: "/svg/shop-gallery-link-arrow.svg",
}]