export const pressAboutSlides = [{
    id: "paS01",
    cite: <>{<a rel="noopener" target="_blank" href="https://www.mother.ly/parenting/how-to-avoid-greenwashing/" />}</>,
    blockquoteText: <>“At TreeHouse we're trying to bring our community on the journey with us, sharing the decisions we are making with our customers (and why), consulting with our base and working together toward the next goal.”</>,
    autor: "/motherly-logo.png",
    autorAlt: "Motherly logo",
    readLink: "https://www.mother.ly/parenting/how-to-avoid-greenwashing/",
    linkText: "READ MORE",
    imgSrc: "/svg/press-about-link-arrow.svg", 
}, {
    id: "paS02",
    cite: <>{<a rel="noopener" href="https://www.westsiderag.com/" />}</>,
    blockquoteText: <> “Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus laboriosam harum aut eum dolores, molestias asperiores. Dolore deserunt eveniet, tenetur sequi, nisi nobis...</>,
    autor: "/west-side-rag-logo.png",
    autorAlt: "West Side Rag logo",
    readLink: "https://www.westsiderag.com/",
    linkText: "READ MORE",
    imgSrc: "/svg/press-about-link-arrow.svg",
}, {
    id: "paS03",
    cite: <>{<a rel="noopener" target="_blank" href="https://www.mother.ly/parenting/how-to-avoid-greenwashing/" />}</>,
    blockquoteText: <>“At TreeHouse we're trying to bring our community on the journey with us, sharing the decisions we are making with our customers (and why), consulting with our base and working together toward the next goal.”</>,
    autor: "/motherly-logo.png",
    autorAlt: "Motherly logo",
    readLink: "https://www.mother.ly/parenting/how-to-avoid-greenwashing/",
    linkText: "READ MORE",
    imgSrc: "/svg/press-about-link-arrow.svg",
}, {
    id: "paS04",
    cite: <>{<a rel="noopener" target="_blank" href="https://www.westsiderag.com/" />}</>,
    blockquoteText: <> “Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus laboriosam harum aut eum dolores, molestias asperiores. Dolore deserunt eveniet, tenetur sequi, nisi nobis...</>,
    autor: "/west-side-rag-logo.png",
    autorAlt: "West Side Rag logo",
    readLink: "https://www.westsiderag.com/",
    linkText: "READ MORE",
    imgSrc: "/svg/press-about-link-arrow.svg",
}, {
    id: "paS05",
    cite: <>{<a rel="noopener" target="_blank" href="https://www.mother.ly/parenting/how-to-avoid-greenwashing/" />}</>,
    blockquoteText: <>“At TreeHouse we're trying to bring our community on the journey with us, sharing the decisions we are making with our customers (and why), consulting with our base and working together toward the next goal.”</>,
    autor: "/motherly-logo.png",
    autorAlt: "Motherly logo",
    readLink: "https://www.mother.ly/parenting/how-to-avoid-greenwashing/",
    linkText: "READ MORE",
    imgSrc: "/svg/press-about-link-arrow.svg", 
}, {
    id: "paS06",
    cite: <>{<a rel="noopener" target="_blank" href="https://www.westsiderag.com/" />}</>,
    blockquoteText: <> “Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus laboriosam harum aut eum dolores, molestias asperiores. Dolore deserunt eveniet, tenetur sequi, nisi nobis...</>,
    autor: "/west-side-rag-logo.png",
    autorAlt: "West Side Rag logo",
    readLink: "https://www.westsiderag.com/",
    linkText: "READ MORE",
    imgSrc: "/svg/press-about-link-arrow.svg", 
}];