export const recommendationsCards02 = [{
    id: "rCard05",
    imgSrc: "/recommendations-image05.jpg",
    imgAlt: "Child T-shirt",
    caption: "Willow Tee",
    stars: "/five-star-rating.png",
    reviews: "1 reviews",
    price: "34.00 USD",
    quickTitle: "QUICK ADD",
    ageSelect2_3: "2-3, ",
    ageSelect3_4: "3-4, ",
    ageSelect4_5: "4-5, ",
    ageSelect5_6: "5-6, ",
    ageSelect6_7: "6-7, ",
    ageSelect7_8: "7-8, ",
    ageSelect8_9: "8-9, ",
    ageSelect9_10: "9-10 years",
    link: "/t-shirt-card-page",
}, {
    id: "rCard06",
    imgSrc: "/recommendations-image06.jpg",
    imgAlt: "Children's shirt with short sleeves",
    caption: "Maple Romper in Canyon Clay",
    stars: "/five-star-rating.png",
    reviews: "3 reviews",
    price: "70.00 USD",
    quickTitle: "QUICK ADD",
    ageSelect2_3: "2-3, ",
    ageSelect3_4: "3-4, ",
    ageSelect4_5: "4-5, ",
    ageSelect5_6: "5-6, ",
    ageSelect6_7: "6-7, ",
    ageSelect7_8: "7-8, ",
    ageSelect8_9: "8-9, ",
    ageSelect9_10: "9-10 years",
    link: "/roomper-card-page",
}, {
    id: "rCard07",
    imgSrc: "/recommendations-image07.jpg",
    imgAlt: "Child T-shirt",
    caption: "Oak Henley Tee",
    stars: "/five-star-rating.png",
    reviews: "2 reviews",
    price: "34.00 USD",
    quickTitle: "QUICK ADD",
    ageSelect2_3: "2-3, ",
    ageSelect3_4: "3-4, ",
    ageSelect4_5: "4-5, ",
    ageSelect5_6: "5-6, ",
    ageSelect6_7: "6-7, ",
    ageSelect7_8: "7-8, ",
    ageSelect8_9: "8-9, ",
    ageSelect9_10: "9-10 years",
    link: "/t-shirt-card-page",
}, {
    id: "rCard08",
    imgSrc: "/recommendations-image08.jpg",
    imgAlt: "Children's trousers with pockets",
    caption: "Gingko Pant in Ripe Olive",
    stars: "/five-star-rating.png",
    reviews: "5 reviews",
    price: "42.00 USD",
    quickTitle: "QUICK ADD",
    ageSelect2_3: "2-3, ",
    ageSelect3_4: "3-4, ",
    ageSelect4_5: "4-5, ",
    ageSelect5_6: "5-6, ",
    ageSelect6_7: "6-7, ",
    ageSelect7_8: "7-8, ",
    ageSelect8_9: "8-9, ",
    ageSelect9_10: "9-10 years",
    link: "/bottom-card-page",
}];