export const recommendationsCards01 = [{
    id: "rCard01",
    imgSrc: "/recommendations-image01.jpg",
    imgAlt: "Children's long sleeve shirt",
    caption: "Birch Shirt in Sand",
    stars: "/five-star-rating.png",
    reviews: "2 reviews",
    price: "45.00 USD",
    quickTitle: "QUICK ADD",
    ageSelect2_3: "2-3, ",
    ageSelect3_4: "3-4, ",
    ageSelect4_5: "4-5, ",
    ageSelect5_6: "5-6, ",
    ageSelect6_7: "6-7, ",
    ageSelect7_8: "7-8, ",
    ageSelect8_9: "8-9, ",
    ageSelect9_10: "9-10 years",
    link: "/shirt-card-page",
}, {
    id: "rCard02",
    imgSrc: "/recommendations-image02.jpg",
    imgAlt: "Child T-shirt",
    caption: "Oak Tee",
    stars: "/five-star-rating.png",
    reviews: "3 reviews",
    price: "34.00 USD",
    quickTitle: "QUICK ADD",
    ageSelect2_3: "2-3, ",
    ageSelect3_4: "3-4, ",
    ageSelect4_5: "4-5, ",
    ageSelect5_6: "5-6, ",
    ageSelect6_7: "6-7, ",
    ageSelect7_8: "7-8, ",
    ageSelect8_9: "8-9, ",
    ageSelect9_10: "9-10 years",
    link: "/t-shirt-card-page",
}, {
    id: "rCard03",
    imgSrc: "/recommendations-image03.jpg",
    imgAlt: "Rompers",
    caption: "Birch Romper in Sleepy Blue",
    stars: "/five-star-rating.png",
    reviews: "1 reviews",
    price: "62.00 USD",
    quickTitle: "QUICK ADD",
    ageSelect2_3: "2-3, ",
    ageSelect3_4: "3-4, ",
    ageSelect4_5: "4-5, ",
    ageSelect5_6: "5-6, ",
    ageSelect6_7: "6-7, ",
    ageSelect7_8: "7-8, ",
    ageSelect8_9: "8-9, ",
    ageSelect9_10: "9-10 years",
    link: "/roomper-card-page",
}, {
    id: "rCard04",
    imgSrc: "/recommendations-image04.jpg",
    imgAlt: "Children's trousers with pockets",
    caption: "Oak Pant in Tassel",
    stars: "/five-star-rating.png",
    reviews: "5 reviews",
    price: "52.00 USD",
    quickTitle: "QUICK ADD",
    ageSelect2_3: "2-3, ",
    ageSelect3_4: "3-4, ",
    ageSelect4_5: "4-5, ",
    ageSelect5_6: "5-6, ",
    ageSelect6_7: "6-7, ",
    ageSelect7_8: "7-8, ",
    ageSelect8_9: "8-9, ",
    ageSelect9_10: "9-10 years",
    link: "/bottom-card-page",
}];