export const shopGallery = [{
    id: "sg01",
    imageSrc: "/shop-gallery-image01.jpg",
    imageAlt: "Girl with a watering can in the garden",
    text: "Сozy chic for the playground",
    arrowIcon: "/svg/shop-gallery-link-arrow.svg",
    linkTo: "/shop-page",
    linkText: "View products",
    imgCard01: "/product-card-image05.jpg",
    imgAlt01: "product",
    titleCard01: "T-shirt Hamra Trees Navy",
    priceCard01: "35.00 USD",
    imgCard02: "/product-card-image06.jpg",
    imgAlt02: "product",
    titleCard02: "T-shirt Hamra Trees Navy",
    priceCard02: "35.00 USD",
}, {
    id: "sg02",
    imageSrc: "/shop-gallery-image02.jpg",
    imageAlt: "Girl with a bouquet of wildflowers",
    text: "Effortless Beach Style",
    arrowIcon: "/svg/shop-gallery-link-arrow.svg",
    linkTo: "/shop-page",
    linkText: "View products",
    imgCard01: "/product-card-image02.jpg",
    imgAlt01: "product",
    titleCard01: "T-shirt Hamra Trees Navy",
    priceCard01: "35.00 USD",
    imgCard02: "/product-card-image01.jpg",
    imgAlt02: "product",
    titleCard02: "T-shirt Hamra Trees Navy",
    priceCard02: "35.00 USD",
}, {
    id: "sg03",
    imageSrc: "/shop-gallery-image03.jpg",
    imageAlt: "Boy in shorts on a tree",
    text: "Forest School Essentials",
    arrowIcon: "/svg/shop-gallery-link-arrow.svg",
    linkTo: "/shop-page",
    linkText: "View products",
    imgCard01: "/product-card-image03.jpg",
    imgAlt01: "product",
    titleCard01: "T-shirt Hamra Trees Navy",
    priceCard01: "35.00 USD",
    imgCard02: "/product-card-image04.jpg",
    imgAlt02: "product",
    titleCard02: "T-shirt Hamra Trees Navy",
    priceCard02: "35.00 USD",
}, {
    id: "sg04",
    imageSrc: "/shop-gallery-image04.jpg",
    imageAlt: "Two girls in the forest",
    text: "Playdate With Friends 5th",
    arrowIcon: "/svg/shop-gallery-link-arrow.svg",
    linkTo: "/shop-page",
    linkText: "View products",
    imgCard01: "/product-card-image02.jpg",
    imgAlt01: "product",
    titleCard01: "T-shirt Hamra Trees Navy",
    priceCard01: "35.00 USD",
    imgCard02: "/product-card-image01.jpg",
    imgAlt02: "product",
    titleCard02: "T-shirt Hamra Trees Navy",
    priceCard02: "35.00 USD",
}, {
    id: "sg05",
    imageSrc: "/shop-gallery-image05.jpg",
    imageAlt: "Girl with a book on her lap",
    text: "Lounging at home",
    arrowIcon: "/svg/shop-gallery-link-arrow.svg",
    linkTo: "/shop-page",
    linkText: "View products",
    imgCard01: "/product-card-image02.jpg",
    imgAlt01: "product",
    titleCard01: "T-shirt Hamra Trees Navy",
    priceCard01: "35.00 USD",
    imgCard02: "/product-card-image01.jpg",
    imgAlt02: "product",
    titleCard02: "T-shirt Hamra Trees Navy",
    priceCard02: "35.00 USD",
}, {
    id: "sg06",
    imageSrc: "/shop-gallery-image01.jpg",
    imageAlt: "Girl with a watering can in the garden",
    text: "Сozy chic for the playground",
    arrowIcon: "/svg/shop-gallery-link-arrow.svg",
    linkTo: "/shop-page",
    linkText: "View products",
    imgCard01: "/product-card-image05.jpg",
    imgAlt01: "product",
    titleCard01: "T-shirt Hamra Trees Navy",
    priceCard01: "35.00 USD",
    imgCard02: "/product-card-image06.jpg",
    imgAlt02: "product",
    titleCard02: "T-shirt Hamra Trees Navy",
    priceCard02: "35.00 USD",
}, {
    id: "sg07",
    imageSrc: "/shop-gallery-image02.jpg",
    imageAlt: "Girl with a bouquet of wildflowers",
    text: "Effortless Beach Style",
    arrowIcon: "/svg/shop-gallery-link-arrow.svg",
    linkTo: "/shop-page",
    linkText: "View products",
    imgCard01: "/product-card-image02.jpg",
    imgAlt01: "product",
    titleCard01: "T-shirt Hamra Trees Navy",
    priceCard01: "35.00 USD",
    imgCard02: "/product-card-image01.jpg",
    imgAlt02: "product",
    titleCard02: "T-shirt Hamra Trees Navy",
    priceCard02: "35.00 USD",
}, {
    id: "sg08",
    imageSrc: "/shop-gallery-image03.jpg",
    imageAlt: "Boy in shorts on a tree",
    text: "Forest School Essentials",
    arrowIcon: "/svg/shop-gallery-link-arrow.svg",
    linkTo: "/shop-page",
    linkText: "View products",
    imgCard01: "/product-card-image03.jpg",
    imgAlt01: "product",
    titleCard01: "T-shirt Hamra Trees Navy",
    priceCard01: "35.00 USD",
    imgCard02: "/product-card-image04.jpg",
    imgAlt02: "product",
    titleCard02: "T-shirt Hamra Trees Navy",
    priceCard02: "35.00 USD",
}, {
    id: "sg09",
    imageSrc: "/shop-gallery-image04.jpg",
    imageAlt: "Two girls in the forest",
    text: "Playdate With Friends 5th",
    arrowIcon: "/svg/shop-gallery-link-arrow.svg",
    linkTo: "/shop-page",
    linkText: "View products",
    imgCard01: "/product-card-image02.jpg",
    imgAlt01: "product",
    titleCard01: "T-shirt Hamra Trees Navy",
    priceCard01: "35.00 USD",
    imgCard02: "/product-card-image01.jpg",
    imgAlt02: "product",
    titleCard02: "T-shirt Hamra Trees Navy",
    priceCard02: "35.00 USD",
}, {
    id: "sg10",
    imageSrc: "/shop-gallery-image05.jpg",
    imageAlt: "Girl with a book on her lap",
    text: "Lounging at home",
    arrowIcon: "/svg/shop-gallery-link-arrow.svg",
    linkTo: "/shop-page",
    linkText: "View products",
    imgCard01: "/product-card-image02.jpg",
    imgAlt01: "product",
    titleCard01: "T-shirt Hamra Trees Navy",
    priceCard01: "35.00 USD",
    imgCard02: "/product-card-image01.jpg",
    imgAlt02: "product",
    titleCard02: "T-shirt Hamra Trees Navy",
    priceCard02: "35.00 USD",
}];